#!/bin/sh

sxhkd &

dunst &

# Polybar(s)
$HOME/.config/polybar/launch.sh

feh --bg-scale $(ls ${HOME}/Pictures/wallpaper.*)

# Rules and Config
#bspc monitor -d term web chat music random

# Global Settings
bspc config active_border_color         "#2e3440"
bspc config focused_border_color        "#4c566a"
bspc config normal_border_color         "#eceff4"
bspc config presel_border_color         "#88c0d0"
bspc config urgent_border_color         "#ebcb8b"

bspc config border_width                3
bspc config window_gap                  32
bspc config split_ratio                 0.50
bspc config automatic_scheme            alternate
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config click_to_focus              true
bspc config focus_by_distance           true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true

# Rules
bspc rule -a KeepassXC follow=on state=floating
bspc rule -a Nvidia-settings follow=on state=floating
bspc rule -a Lxappearance  follow=on state=floating
bspc rule -a Pavucontrol  follow=on state=floating
