#!/bin/sh

sxhkd &

dunst &

# Polybar(s)
$HOME/.config/polybar/launch.sh

feh --bg-scale "$(< "${HOME}/Pictures/wallpaper.*")"

# Rules and Config
bspc monitor -d TERM WEB CHAT MUSIC

# Global Settings
#bspc config normal_border_color ""
#bspc config focused_border_color ""
#bspc config urgent_border_color ""
#bspc config presel_border_color ""

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a TelegramDesktop desktop='^2' follow=on
bspc rule -a Spotify desktop='^5' follow=on state=floating

bspc rule -a Nvidia-settings follow=on state=floating
bspc rule -a Lxappearance  follow=on state=floating
bspc rule -a Pavucontrol  follow=on state=floating
