#!/bin/sh

sxhkd &

dunst &

$HOME/.config/polybar/launch.sh &
feh --bg-scale "$(< "${HOME}/Pictures/wallpaper.*")"
compton --config "$HOME/.config/compton.conf" -b &
#/usr/bin/firefox &


# Rules and Config
bspc monitor -d WEB TELEGRAM TERM FILES MUSIC

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a TelegramDesktop desktop='^2' follow=on
bspc rule -a Spotify desktop='^5' follow=on state=floating

bspc rule -a Nvidia-settings follow=on state=floating
bspc rule -a Lxappearance  follow=on state=floating
bspc rule -a Pavucontrol  follow=on state=floating

bspc config focus_follows_pointer true
